name: Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build binaries
        run: make

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/radar-linux
            build/radar-mac
            build/radar-windows.exe
